apiVersion: v1
kind: Service
metadata:
  name: time-attendance-api
spec:
  selector:
    app: time-attendance-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 